### ISSUE TITLE
Multiple users RStudio Server

### ISSUE THREAD

**Issue by decisoft** [davetang/learning_docker#2]
Hi, @davetang!

Thanks for your amazing work. I've been using your image of RStudio-Server for months and it works great. Now, the last couple of days I've been trying to add users to the server and (the most important), make it persistent.

From my point of view, the best method is to add the users into the Dockerfile, but it always raises problems with the default user rstudio. Obviously, doing it through docker exec -it rstudio_server /bin/bash works but until the next recreation/restart of the container.

Could you suggest any method to do that?
Thanks

**Comment by davetang** [comment]
Hi there!

you can add a user or users via the Dockerfile. For example:

    FROM rocker/rstudio:4.2.2
    RUN useradd --create-home --shell /bin/bash testuser && echo 'testuser:password' | chpasswd

I've tested this and can confirm that I can log in as testuser/password on the Rstudio Server login page.

Let me know if this works for you.

Cheers,
Dave

**Comment by davetang** [comment]
Alternatively, don't use the `--rm` argument and use `--restart always` when you use `docker run`. Then once your container has started, add the user manually.

```bash
docker exec -it container_name /bin/bash
useradd --create-home --shell /bin/bash testuser && echo 'testuser:password' | chpasswd
```

When your container or Docker restarts, `testuser` should still be there.

**Comment by decisoft** [comment]
Thanks for the response. I've tried the first option, specifying in the Dockerfile the user, and now it doesn't show Incorrect username/password, but instead it shows "Unable to connect to the R session on RStudio Server", after a few seconds trying to load. 

The logs of the container:
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 01_set_env: executing... 
> skipping /var/run/s6/container_environment/HOME
> skipping /var/run/s6/container_environment/PASSWORD
> skipping /var/run/s6/container_environment/RSTUDIO_VERSION
> [cont-init.d] 01_set_env: exited 0.
> [cont-init.d] 02_userconf: executing... 
> deleting the default user
> creating new rstudio with UID 1013
> useradd: warning: the home directory /home/rstudio already exists.
> useradd: Not copying any file from skel directory into it.
> Modifying primary group rstudio
> Primary group ID is now custom_group 1014
> [cont-init.d] 02_userconf: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.

In the Dockerfile, I added the following:
```
ARG bioc_ver=3.16

RUN useradd --create-home --shell /bin/bash decisoft && echo 'decisoft:password' | chpasswd
```
And then workdir. Am I missing something? Thanks :)

**Comment by davetang** [comment]
Does this minimal example work?

`Dockerfile_useradd`

    FROM rocker/rstudio:4.2.2
    RUN useradd --create-home --shell /bin/bash decisoft && echo 'decisoft:password' | chpasswd

Docker commands:

    docker --version
    # Docker version 20.10.22, build 3a2c30b
    docker build -t rstudio_decisoft -f Dockerfile_useradd .
    docker run -d -p 8888:8787 rstudio_decisoft

Open browser

    http://localhost:8888/

<img width="332" alt="Screenshot 2023-01-27 at 21 11 08" src="https://user-images.githubusercontent.com/2980289/215084123-83c4bd0f-c797-4e9c-afd2-f3ed280c3641.png">

Works for me.

**Comment by decisoft** [comment]
Hi again :)

Yes, that minimal example just works. Just after that, I compare your Dockerfile with the minimal one, and then I realised that the error causing not starting R was a mistake while mapping the home of hosts users to the home of the users of the container. I was mapping `/home/decisoft:/home/decisoft` and it has to be `/home/decisoft:/home/decisoft/work`. Now it works! With multiple users :)

Thanks for everything!

**Comment by davetang** [comment]
No worries and I'm glad it is working! I'll close the issue now.

**Comment by nikofleischer** [comment]
Is it possible to combine multiple users with a joint pkgcache for renv? 
so far I have been mapping `USERID` and `GROUPID` to `1001` via docker compose, but I don't know if that is sustainable with muliple rstudio users.

**Comment by davetang** [comment]
@nikofleischer I've never used {renv}; I just had a look at https://rstudio.github.io/renv/articles/renv.html and I guess {renv} is like an R equivalent of Conda environments.

So I just wanted to ask what is the purpose of pkgcache and also what you are trying to achieve?

**Comment by nikofleischer** [comment]
@davetang renv is a little bit similar to Conda in that in manages R packages, yes. It runs inside R studio projects. It will record all the dependencies of a project into a renv.lock file. This includes R Versions, Package Versions, Bioconductor and so on. Whenever you want to replicate a working environment, you just share the lock file and renv takes care of the rest. 

It does that by storing packages in a folder within each project, allowing for many different combinations of package versions to exist in parallel within one R install. One of the neat features, is that it constructs a cache to store package binaries in, linking installed packages to this cache instead of downloading them again. 

When you have to spin up many different set ups continously this makes working much easier. Within docker it's also nice not having to use different containers for different projects at least during the development phase. 

In my single user docker setup I map user and group ids to 1001 which is the same as the host user and just mount this pkgcache into the container, so I can use it across multiple containers. 

Now I want to set up a workshop for our students, where it would be nice if they could all connect independently to R Studio Server and also use the pkgcache in case they need to install a package during the workshop quickly. 

But what I am asking for is not unique to renv, basically just having a bind mount that all users can access in a multiuser rstudio server setup as you described above. Home directories are automatically only accessible to each user so this is fine. 

Best, Niko

**Comment by davetang** [comment]
@nikofleischer thank you for the explanation and for bringing {renv} to my attention. I looked into the documentation a bit more and I think I'll start using it for my own work!

After looking into it, I guess I understand a bit more about what you want to achieve.

* Create a multi-user image.
* Run the image and have your students log onto RStudio Server using the already created users.
* The users should be using the same cache to ease the installation of packages.

Does the suggestion at https://rstudio.github.io/renv/articles/package-install.html#cache-location work?

> If you’d like to share the package cache across multiple users, you can do so by setting the RENV_PATHS_CACHE environment variable to a shared path. This variable should be set in an R startup file to make it apply to all R sessions. While you can set it in a project-local .Renviron, or the user-level ~/.Renviron, we generally recommend using the R installation’s site-wide Renviron.site if you’d like to ensure the same cache path is visible to all users of R on a system.

So in your case you would set `RENV_PATHS_CACHE` to the bind mount that contains your cache.

There is more at https://rstudio.github.io/renv/articles/package-install.html#shared-cache-locations.

I don't know how well this works if multiple people are trying to write to the same cache. I suppose {renv} has some mechanism in place since they expected users to share caches.
